apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ore-pvc-redis
  namespace: ore-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
---