---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-prod
  namespace: ore
data:
  # General
  STAGE: Production
  LOGGING_LEVEL: DEBUG

  # Cleos
  CLEOS_URL: https://ore.openrights.exchange

  # CoinMarketCap API
  CMC_EMAIL: james@aikon.com"
  CMC_API_ENDPOINT: https://pro-api.coinmarketcap.com
  CMC_API_KEY: d4455be6-981a-4de3-8929-8851d0006a27
  CMC_API_RESET_TIME: "260"

  # Telegram API
  TELEGRAM_BOT_API_KEY: 5017222691:AAHy9sFom0E4_FrxEkuGM6X5vQM8SIkxjtE
  TELEGRAM_BOT_NAME: ORE_TIP_BOT

  # Testing
  TEST_USER_OREID: ore1shlejxsp
  TEST_USER_EMAIL: james@aikon.com
  CRYPTO_PASSWORD: pizzatimeninjass

  # Redis
  REDIS_HOST: redis-prod
  REDIS_PORT: "6379"

  # Git
  GIT_TOKEN: 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
