apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-prod
  namespace: ore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: backend
      env: production
  template:
    metadata:
      labels:
        app: redis
        tier: backend
        env: production
    spec:
      # initContainers:
      # - name: disable-thp
      #   image: boyroywax/ore-redis-prod:latest
      #   volumeMounts:
      #     - name: host-sys
      #       mountPath: /host-sys
      #   command: ["sh", "-c", "echo 'never' >/host-sys/kernel/mm/transparent_hugepage/enabled"]
      containers:
      - image: boyroywax/ore-redis-prod:latest
        name: redis-prod
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 1
          periodSeconds: 4
        volumeMounts:
        # - mountPath: /sys
        #   name: host-sys
        #   readOnly: false
        - mountPath: /data
          name: redis-vol1
          readOnly: false
          subPath: ore/redis
        # securityContext:
        #   runAsUser: 1001
        #   runAsNonRoot: true
      volumes:
      - name: redis-vol1
        persistentVolumeClaim:
          claimName: ore-pvc-redis
      # - name: host-sys
      #   hostPath:
      #     path: /sys
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis-prod
  namespace: ore
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    env: production
---