apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ore-pvc-bot
  namespace: ore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
---