---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tipbot-telegram-prod
  namespace: ore
  labels:
    app: tipbot
    tier: frontend
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tipbot
      tier: frontend
      env: production
  template:
    metadata:
      labels:
        app: tipbot
        tier: frontend
        env: production
    spec:
      containers:
      - name: tipbot-telegram-prod
        image: boyroywax/ore-bot-telegram-prod:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        volumeMounts:
        - mountPath: /home/app/web/meme_entries
          name: bot-vol1
          readOnly: false
          subPath: ore/meme_entries
        envFrom:
          - configMapRef:
              name: config-prod
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
        ports:
        - containerPort: 80
          name: telegram-port
          protocol: UDP
      restartPolicy: Always

      volumes:
      - name: bot-vol1
        persistentVolumeClaim:
          claimName: ore-pvc-bot

---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: ore
spec:
  ports:
  - name: telegram-port
    port: 80
    protocol: UDP
    targetPort: 80
  selector:
    app: tipbot
    tier: frontend
    env: production
  type: ClusterIP
---